package edu.ithaca.dragon.tecmap.io.reader;

import edu.ithaca.dragon.tecmap.Settings;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.util.Arrays;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;

class CsvRepresentationTest {

    @Test
    void parseAllRowsFromFileTest() throws IOException {
        List<String[]> rows = CsvRepresentation.parseRowsFromFile(Settings.DEFAULT_TEST_DATASTORE_PATH + "Cs1Example/Cs1ExampleAssessment1.csv");
        assertEquals("student ID", rows.get(0)[0]);
        assertEquals("", rows.get(1)[0]);
        assertEquals("Lisa", rows.get(3)[1]);
        assertEquals("75", rows.get(4)[6]);
    }

    @Test
    void writeRowsToFileTest() throws IOException{
        List<String[]> rows = CsvRepresentation.parseRowsFromFile(Settings.DEFAULT_TEST_DATASTORE_PATH + "Cs1Example/Cs1ExampleAssessment1.csv");
        //change some stuff to wrote to the file
        rows.get(2)[0] ="s100";
        rows.get(3)[6] ="50";
        CsvRepresentation.writeRowsToFile(rows, Settings.DEFAULT_TEST_DATASTORE_PATH+"autogenerated/CsvRepresentationTest-writeRowsToFileTest.csv");
        rows = CsvRepresentation.parseRowsFromFile(Settings.DEFAULT_TEST_DATASTORE_PATH+"autogenerated/CsvRepresentationTest-writeRowsToFileTest.csv");
        //expect changes
        assertEquals("s100", rows.get(2)[0]);
        assertEquals("50", rows.get(3)[6]);
        //expect other values the same
        assertEquals("student ID", rows.get(0)[0]);
        assertEquals("75", rows.get(4)[6]);

        File tempFile = new File(Settings.DEFAULT_TEST_DATASTORE_PATH+"autogenerated/CsvRepresentationTest-writeRowsToFileTest.csv");
        if (!tempFile.delete()){
            fail("File did not exist to delete");
        }
    }

}